### ISSUE TITLE
Demo fails to run with SA 1.1.1

### ISSUE THREAD

**Issue by austinlparker** [opentracing-contrib/java-specialagent-demo#3]
When I try to run the `run-with-lightstep` make target and SA 1.1.1 (I changed the SA JAR in the makefile), I get the following errors -

```
java -cp target/api-1.0-SNAPSHOT.jar -javaagent:opentracing-specialagent-1.1.1.jar \
		-Dspecialagent.tracer=lightstep \
		-Dspecialagent.log.level=INFO \
		-Dtracer.configurationFile=ls_tracer.properties \
		-Dls.componentName=Microdonuts \
		com.otsample.api.App
2019-05-07 06:52:28.175:INFO::main: Logging initialized @14089ms to org.eclipse.jetty.util.log.StdErrLog
2019-05-07 06:52:31.408:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2019-05-07 06:52:31.637:INFO:oejsh.ContextHandler:main: Started o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE}
2019-05-07 06:52:31.731:INFO:oejsh.ContextHandler:main: Started c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE}
2019-05-07 06:52:31.731:INFO:oejsh.ContextHandler:main: Started c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE}
2019-05-07 06:52:32.007:INFO:oejs.AbstractConnector:main: Started ServerConnector@73c5ffb4{HTTP/1.1,[http/1.1]}{0.0.0.0:10001}
2019-05-07 06:52:32.008:INFO:oejs.Server:main: Started @17955ms
org.eclipse.jetty.server.Server@4ebea736 - STARTED
 += qtp93126017{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   +- 16 qtp93126017-16 RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   +- 20 qtp93126017-20 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 17 qtp93126017-17-acceptor-0@49303e91-ServerConnector@73c5ffb4{HTTP/1.1,[http/1.1]}{0.0.0.0:10001} RUNNABLE @ sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) prio=3
 |   +- 19 qtp93126017-19 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 18 qtp93126017-18 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 14 qtp93126017-14 RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   +- 15 qtp93126017-15 RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   +- 13 qtp93126017-13 RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   +- jobs
 += ServerConnector@73c5ffb4{HTTP/1.1,[http/1.1]}{0.0.0.0:10001} - STARTED
 |   +~ org.eclipse.jetty.server.Server@4ebea736 - STARTED
 |   +~ qtp93126017{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@6d5f824d - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@1abea9f9
 |   += HttpConnectionFactory@65ea5213[HTTP/1.1] - STARTED
 |   |   +- HttpConfiguration@6199a63d{32768/8192,8192/8192,https://:0,[]}
 |   += org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@1d47cdcc - STARTED
 |   |   += org.eclipse.jetty.io.ManagedSelector@54e7a5d5 id=0 keys=0 selected=0 id=0
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@2c62c767 keys=0
 |   |   += org.eclipse.jetty.io.ManagedSelector@507ae2bd id=1 keys=0 selected=0 id=1
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@269aac17 keys=0
 |   |   += org.eclipse.jetty.io.ManagedSelector@59b2192f id=2 keys=0 selected=0 id=2
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@6e38fb8e keys=0
 |   |   += org.eclipse.jetty.io.ManagedSelector@410e4d5f id=3 keys=0 selected=0 id=3
 |   |       +- sun.nio.ch.KQueueSelectorImpl@51ad19b2 keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:10001]
 |   +- qtp93126017-17-acceptor-0@49303e91-ServerConnector@73c5ffb4{HTTP/1.1,[http/1.1]}{0.0.0.0:10001}
 += org.eclipse.jetty.server.handler.ContextHandlerCollection@723877b3[o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE}, c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE}, c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE}] - STARTED
 |   += o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE} - STARTED
 |   |   += org.eclipse.jetty.server.handler.ResourceHandler@75501c43 - STARTED
 |   |   |
 |   |   +> No ClassLoader
 |   |   +> Handler attributes o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE}
 |   |   |   +- org.eclipse.jetty.server.Executor=qtp93126017{STARTED,8<=11<=200,i=2,q=0}
 |   |   +> Context attributes o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE}
 |   |   +> Initparams o.e.j.s.h.ContextHandler@4cff7acb{/,null,AVAILABLE}
 |   += c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE} - STARTED
 |   |   += org.eclipse.jetty.servlet.ServletHandler@2600e937 - STARTED
 |   |   |   += tracingFilter - STARTED
 |   |   |   +- [/*]/[]==31=>tracingFilter
 |   |   |   += com.otsample.api.ApiContextHandler$OrderServlet-6c379416@10613092==com.otsample.api.ApiContextHandler$OrderServlet,jsp=null,order=-1,inst=true - STARTED
 |   |   |   +- [/order]=>com.otsample.api.ApiContextHandler$OrderServlet-6c379416
 |   |   |   += com.otsample.api.ApiContextHandler$StatusServlet-5594f0c7@e5253e8==com.otsample.api.ApiContextHandler$StatusServlet,jsp=null,order=-1,inst=true - STARTED
 |   |   |   +- [/status]=>com.otsample.api.ApiContextHandler$StatusServlet-5594f0c7
 |   |   |   += org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-54ac790a@489e24a8==org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false - STARTED
 |   |   |   +- [/]=>org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-54ac790a
 |   |   |
 |   |   +> No ClassLoader
 |   |   +> Handler attributes c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE}
 |   |   |   +- org.eclipse.jetty.server.Executor=qtp93126017{STARTED,8<=11<=200,i=2,q=0}
 |   |   +> Context attributes c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE}
 |   |   |   +- org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=1]
 |   |   |   +- io.opentracing.Tracer=GlobalTracer{NoopTracer}
 |   |   +> Initparams c.o.a.ApiContextHandler@18fb6d06{/,null,AVAILABLE}
 |   += c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE} - STARTED
 |       += org.eclipse.jetty.servlet.ServletHandler@3a352dd5 - STARTED
 |       |   += tracingFilter - STARTED
 |       |   +- [/*]/[]==31=>tracingFilter
 |       |   += com.otsample.api.KitchenContextHandler$AddDonutServlet-bf0568b@88ddd003==com.otsample.api.KitchenContextHandler$AddDonutServlet,jsp=null,order=-1,inst=true - STARTED
 |       |   +- [/add_donut]=>com.otsample.api.KitchenContextHandler$AddDonutServlet-bf0568b
 |       |   += com.otsample.api.KitchenContextHandler$CheckDonutsServlet-5409b9e3@cc349763==com.otsample.api.KitchenContextHandler$CheckDonutsServlet,jsp=null,order=-1,inst=true - STARTED
 |       |   +- [/check_donuts]=>com.otsample.api.KitchenContextHandler$CheckDonutsServlet-5409b9e3
 |       |   += org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-62f31489@4c93e1c1==org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false - STARTED
 |       |   +- [/]=>org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-62f31489
 |       |
 |       +> No ClassLoader
 |       +> Handler attributes c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE}
 |       |   +- org.eclipse.jetty.server.Executor=qtp93126017{STARTED,8<=11<=200,i=2,q=0}
 |       +> Context attributes c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE}
 |       |   +- org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=1]
 |       |   +- io.opentracing.Tracer=GlobalTracer{NoopTracer}
 |       +> Initparams c.o.a.KitchenContextHandler@20010d37{/kitchen,null,AVAILABLE}
 += org.eclipse.jetty.server.handler.ErrorHandler@1b5d32f5 - STARTED
 |
 +> sun.misc.Launcher$AppClassLoader@18b4aac2
     +- file:/Users/austinparker/workspace/java-specialagent-demo/microdonuts/target/api-1.0-SNAPSHOT.jar
     +- file:/Users/austinparker/workspace/java-specialagent-demo/microdonuts/opentracing-specialagent-1.1.1.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-web-servlet-filter-0.2.3.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-specialagent-web-servlet-filter-1.1.1.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-specialagent-concurrent-1.1.1.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-okhttp3-0.1.0.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-concurrent-0.1.0.jar
     +- file:/private/var/folders/tj/cx_5ggyx4db4lvrj9k1wdkph0000gn/T/opentracing-specialagent96111649258832700/META-INF/opentracing-specialagent/opentracing-specialagent-okhttp-1.1.1.jar
     +- sun.misc.Launcher$ExtClassLoader@2fb0623e
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar
         +- file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar
         +- file:/System/Library/Java/Extensions/MRJToolkit.jar
```

In addition, I get the following error if I attempt to dynamically attach the SA 1.1.1 JAR -

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at io.opentracing.contrib.specialagent.SpecialAgent.main(SpecialAgent.java:145)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
Here's the output of `java -version`:
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by malafeev** [comment]
not fails on 1.3.2

**Comment by austinlparker** [comment]
Confirmed that this works in new version. Thanks!
