### ISSUE TITLE
Error: jaeger did not resolve to a tracer JAR or name

### ISSUE THREAD

**Issue by nsreenath** [opentracing-contrib/java-specialagent-demo#8]
I am using Windows 10 and didn't have `make` installed. So I directly run `mvn package` and then run the following java command and got the following error.

`java -cp target/api-1.0-SNAPSHOT-shaded.jar -javaagent:opentracing-specialagent-1.3.1.jar -Dsa.tracer=jaeger -Dsa.log.level=INFO -DJAEGER_SERVICE_NAME=Microdonuts com.otsample.api.App`

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.IllegalStateException: TRACER_PROPERTY=jaeger did not resolve to a tracer JAR or name
        at io.opentracing.contrib.specialagent.SpecialAgent.loadTracer(SpecialAgent.java:503)
        at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:255)
        at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:103)
        at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:166)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

What could be the issue ?

**Comment by zlay0701** [comment]
you can user MinGW in Windows 10 

see  https://blog.csdn.net/C2681595858/article/details/85554359

**Comment by nsreenath** [comment]
Yes, but the issue is not related to make file.
